version: '2'

networks:
  172.31.0.0:
    external: true

services:
  basic_service:
    build:
      dockerfile: docker/Dockerfile.dev
      context: .
    restart: always
    volumes:
      - ./symfony:/var/www/symfony
    container_name: basic_service
    hostname: basic_service
    environment:
      - REDIS_ADDR=redis://basic_redis
      - DATABASE_URL=postgres://test:test@basic_postgres:5432/test?serverVersion=12&charset=utf8

    ports:
    - 9191:9000
    links:
      - basic_postgres
      - basic_redis
    networks:
      - 172.31.0.0

  basic_redis:
    image: redis:5.0.7
    hostname: basic_redis
    container_name: basic_redis
    networks:
      - 172.31.0.0

  basic_postgres:
    image: postgres:12.4-alpine
    hostname: basic_postgres
    container_name: basic_postgres
    restart: always
    ports:
      - 5432
    networks:
      - 172.31.0.0
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  basic_elasticsearch:
    image: sebp/elk:792
    hostname: basic_elasticsearch
    container_name: basic_elasticsearch
    ports:
      - 9200:9200
    networks:
      - 172.31.0.0
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
    networks:
      - 172.31.0.0
  kafka:
      hostname: kafka
      container_name: kafka
      image: wurstmeister/kafka:latest
      ports:
        - "9090:9090"
        - "9091:9091"
        - "9092:9092"
        - "9093:9093"
        - "9094:9094"
      depends_on:
        - zookeeper
      environment:
        KAFKA_CREATE_TOPICS: notifications:1:1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      networks:
        - 172.31.0.0